//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KODLAR
    {
        public int ID { get; set; }
        public string FirmaKod1 { get; set; }
        public string FirmaKod2 { get; set; }
        public string FirmaKod3 { get; set; }
    }
}
