//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FATURABILGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FATURABILGI()
        {
            this.TBL_FATURADETAY = new HashSet<TBL_FATURADETAY>();
        }
    
        public int FaturaBilgiID { get; set; }
        public string Seri { get; set; }
        public string SiraNo { get; set; }
        public string Tarih { get; set; }
        public string Saat { get; set; }
        public string VergiDaire { get; set; }
        public string Alici { get; set; }
        public string TeslimEden { get; set; }
        public string TeslimAlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FATURADETAY> TBL_FATURADETAY { get; set; }
    }
}
