//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOTLAR
    {
        public int ID { get; set; }
        public string Tarih { get; set; }
        public string Saat { get; set; }
        public string Baslik { get; set; }
        public string Detay { get; set; }
        public string Olusturan { get; set; }
        public string Hitap { get; set; }
    }
}
