//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MUSTERIHAREKETLER
    {
        public int HareketID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<byte> Adet { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<short> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public string Tarih { get; set; }
        public string Notlar { get; set; }
    
        public virtual TBL_MUSTERILER TBL_MUSTERILER { get; set; }
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
        public virtual TBL_URUNLER TBL_URUNLER { get; set; }
    }
}
